import React, { useState } from 'react';
import { generateTestPDF } from '../utils/pdfGenerator';
import { X, Sparkles, FilePlus } from 'lucide-react';

interface PDFGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
  onGenerated: (bytes: Uint8Array, fileName: string) => void;
}

export const PDFGeneratorModal: React.FC<PDFGeneratorModalProps> = ({
  isOpen,
  onClose,
  onGenerated,
}) => {
  const [title, setTitle] = useState('Laughing Adventure Custom Test PDF');
  const [author, setAuthor] = useState('Jakob Axel Paper');
  const [subject, setSubject] = useState('Custom PDF Engine Verification Test');
  const [numPages, setNumPages] = useState<number>(1);
  const [showColorBars, setShowColorBars] = useState(true);
  const [showTypeScale, setShowTypeScale] = useState(true);
  const [showGrid, setShowGrid] = useState(true);
  const [showTable, setShowTable] = useState(true);

  if (!isOpen) return null;

  const handleGenerate = (downloadImmediate: boolean = false) => {
    const pagesArray = [];
    for (let i = 0; i < numPages; i++) {
      pagesArray.push({
        title: `${title} - Page ${i + 1}`,
        contentLines: [
          `Custom test sheet ${i + 1} generated by laughing-adventure suite.`,
          `Author: ${author} | Subject: ${subject}`,
          `Generated at: ${new Date().toLocaleString()}`,
        ],
        showColorBars: showColorBars && (i === 0 || numPages === 1),
        showTypeScale: showTypeScale,
        showGrid: showGrid && (i === 0 || numPages === 1),
        showTable: showTable,
      });
    }

    const bytes = generateTestPDF({
      title,
      author,
      subject,
      pages: pagesArray,
    });

    const fileName = `${title.toLowerCase().replace(/[^a-z0-9]/g, '-')}.pdf`;

    if (downloadImmediate) {
      const blob = new Blob([bytes], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = fileName;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }

    onGenerated(bytes, fileName);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs">
      <div className="bg-white rounded-2xl border border-slate-200 shadow-2xl w-full max-w-lg overflow-hidden animate-in fade-in duration-200">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between bg-slate-50/60">
          <div className="flex items-center gap-2">
            <div className="p-1.5 bg-blue-100 text-blue-600 rounded-lg">
              <FilePlus className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-900">Custom Test PDF Generator</h3>
              <p className="text-xs text-slate-500">Synthesize customized test sheets on the fly</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Form Body */}
        <div className="p-6 space-y-4">
          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1">Document Title</label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none"
              placeholder="e.g. Laughing Adventure Test Document"
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">Author Name</label>
              <input
                type="text"
                value={author}
                onChange={(e) => setAuthor(e.target.value)}
                className="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none"
                placeholder="Jakob Axel Paper"
              />
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">Page Count</label>
              <select
                value={numPages}
                onChange={(e) => setNumPages(parseInt(e.target.value, 10))}
                className="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none bg-white"
              >
                <option value={1}>1 Page (Standard)</option>
                <option value={2}>2 Pages (Multi-page)</option>
                <option value={3}>3 Pages (Report)</option>
              </select>
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1">Subject / Notes</label>
            <input
              type="text"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              className="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none"
              placeholder="PDF Conformance Test Profile"
            />
          </div>

          {/* Test Pattern Modules */}
          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-2">
              Diagnostic Test Modules to Include
            </label>
            <div className="grid grid-cols-2 gap-2">
              <label className="flex items-center gap-2 p-2.5 rounded-lg border border-slate-200 hover:bg-slate-50 cursor-pointer transition-colors">
                <input
                  type="checkbox"
                  checked={showColorBars}
                  onChange={(e) => setShowColorBars(e.target.checked)}
                  className="rounded text-blue-600 focus:ring-blue-500"
                />
                <span className="text-xs font-medium text-slate-700">RGB Calibration Bars</span>
              </label>

              <label className="flex items-center gap-2 p-2.5 rounded-lg border border-slate-200 hover:bg-slate-50 cursor-pointer transition-colors">
                <input
                  type="checkbox"
                  checked={showTypeScale}
                  onChange={(e) => setShowTypeScale(e.target.checked)}
                  className="rounded text-blue-600 focus:ring-blue-500"
                />
                <span className="text-xs font-medium text-slate-700">Typography Scale (8-16pt)</span>
              </label>

              <label className="flex items-center gap-2 p-2.5 rounded-lg border border-slate-200 hover:bg-slate-50 cursor-pointer transition-colors">
                <input
                  type="checkbox"
                  checked={showGrid}
                  onChange={(e) => setShowGrid(e.target.checked)}
                  className="rounded text-blue-600 focus:ring-blue-500"
                />
                <span className="text-xs font-medium text-slate-700">Vector Stroke Calibration</span>
              </label>

              <label className="flex items-center gap-2 p-2.5 rounded-lg border border-slate-200 hover:bg-slate-50 cursor-pointer transition-colors">
                <input
                  type="checkbox"
                  checked={showTable}
                  onChange={(e) => setShowTable(e.target.checked)}
                  className="rounded text-blue-600 focus:ring-blue-500"
                />
                <span className="text-xs font-medium text-slate-700">Tabular Data Matrix</span>
              </label>
            </div>
          </div>
        </div>

        {/* Footer actions */}
        <div className="px-6 py-4 border-t border-slate-100 bg-slate-50 flex items-center justify-end gap-2.5">
          <button
            onClick={onClose}
            className="px-4 py-2 text-xs font-semibold text-slate-600 hover:text-slate-800 transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={() => handleGenerate(false)}
            className="px-4 py-2 text-xs font-semibold text-white bg-blue-600 hover:bg-blue-700 rounded-lg shadow-sm transition-colors flex items-center gap-1.5"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>Generate & Test in Viewer</span>
          </button>
        </div>
      </div>
    </div>
  );
};
