/**
 * Pure TypeScript ISO 32000-1 compliant PDF 1.4 Generator.
 * Creates valid, uncompressed or standard stream PDF binary documents for testing.
 */

export interface PDFGenOptions {
  title: string;
  author?: string;
  subject?: string;
  creator?: string;
  pages?: Array<{
    title: string;
    contentLines: string[];
    showColorBars?: boolean;
    showTypeScale?: boolean;
    showGrid?: boolean;
    showTable?: boolean;
  }>;
}

// Helper to format string into PDF escaped literal string
function escapePdfText(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

export function generateTestPDF(options: PDFGenOptions): Uint8Array {
  const title = options.title || 'Laughing Adventure - Test PDF';
  const author = options.author || 'Jakob Axel Paper';
  const subject = options.subject || 'PDF Conformance and Rendering Test Document';
  const creator = options.creator || 'laughing-adventure PDF Engine';
  const creationDate = 'D:' + new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14) + "Z00'00'";

  const pages = options.pages && options.pages.length > 0 ? options.pages : [
    {
      title: 'Laughing Adventure: Test PDF Document',
      contentLines: [
        'This document is a formal test PDF generated to verify PDF rendering engines,',
        'font rasterizers, vector path interpreters, and document metadata parsers.',
        '',
        'Target Repository: AxelJohnson1988/laughing-adventure',
        'Licensing: MIT License (c) Jakob Axel Paper',
        'Standard: PDF-1.4 Conformance Test Profile'
      ],
      showColorBars: true,
      showTypeScale: true,
      showGrid: true,
      showTable: true
    }
  ];

  // We will build objects list
  // Object 1: Catalog
  // Object 2: Outlines
  // Object 3: Pages tree
  // Object 4: Font Helvetica
  // Object 5: Font Helvetica-Bold
  // Object 6: Font Courier
  // Page objects and content objects will follow
  const objects: string[] = [];
  const pageObjIds: number[] = [];
  let nextObjId = 7; // 1 to 6 reserved

  // Generate page stream contents
  const pageContents: { contentId: number; stream: string }[] = [];

  for (let i = 0; i < pages.length; i++) {
    const p = pages[i];
    const pageId = nextObjId++;
    const contentId = nextObjId++;
    pageObjIds.push(pageId);

    // Build PostScript / PDF graphic operations stream
    const ops: string[] = [];

    // Header banner background
    ops.push('q'); // save state
    ops.push('0.93 0.95 0.98 rg'); // soft blue fill
    ops.push('36 732 540 60 re f'); // banner rect

    ops.push('0.15 0.23 0.36 RG 1.5 w'); // dark border
    ops.push('36 732 540 60 re S');

    // Title text
    ops.push('BT');
    ops.push('/F2 18 Tf'); // Bold
    ops.push('0.09 0.16 0.28 rg');
    ops.push('50 765 Td');
    ops.push(`(${escapePdfText(p.title)}) Tj`);
    ops.push('ET');

    // Subtitle / Page marker
    ops.push('BT');
    ops.push('/F1 10 Tf');
    ops.push('0.38 0.44 0.54 rg');
    ops.push('50 745 Td');
    ops.push(`(Page ${i + 1} of ${pages.length}  |  Generated by laughing-adventure test suite) Tj`);
    ops.push('ET');
    ops.push('Q'); // restore state

    // Content text lines
    let yPos = 705;
    if (p.contentLines && p.contentLines.length > 0) {
      ops.push('BT');
      ops.push('/F1 11 Tf');
      ops.push('0.12 0.15 0.18 rg');
      ops.push(`50 ${yPos} Td`);
      for (let j = 0; j < p.contentLines.length; j++) {
        const line = p.contentLines[j];
        if (j > 0) {
          ops.push(`0 -16 Td`);
          yPos -= 16;
        }
        ops.push(`(${escapePdfText(line)}) Tj`);
      }
      ops.push('ET');
      yPos -= 25;
    }

    // Color bars test
    if (p.showColorBars) {
      ops.push('q');
      // Section title
      ops.push('BT');
      ops.push('/F2 11 Tf');
      ops.push('0.12 0.15 0.18 rg');
      ops.push(`50 ${yPos} Td`);
      ops.push('(1. Primary & Secondary Calibration Color Spectrum) Tj');
      ops.push('ET');
      yPos -= 18;

      const colors = [
        { r: 0.88, g: 0.12, b: 0.12, name: 'Red' },
        { r: 0.95, g: 0.55, b: 0.05, name: 'Orange' },
        { r: 0.95, g: 0.80, b: 0.10, name: 'Yellow' },
        { r: 0.15, g: 0.68, b: 0.38, name: 'Green' },
        { r: 0.08, g: 0.52, b: 0.88, name: 'Blue' },
        { r: 0.45, g: 0.20, b: 0.75, name: 'Purple' },
        { r: 0.12, g: 0.12, b: 0.12, name: 'Black' },
        { r: 0.60, g: 0.60, b: 0.60, name: 'Gray 50%' },
      ];

      const barW = 60;
      const barH = 24;
      for (let c = 0; c < colors.length; c++) {
        const col = colors[c];
        const bx = 50 + c * (barW + 7);
        // fill
        ops.push(`${col.r} ${col.g} ${col.b} rg`);
        ops.push(`${bx} ${yPos - barH} ${barW} ${barH} re f`);
        // stroke border
        ops.push('0.2 0.2 0.2 RG 0.5 w');
        ops.push(`${bx} ${yPos - barH} ${barW} ${barH} re S`);

        // label
        ops.push('BT');
        ops.push('/F3 8 Tf');
        ops.push('0.2 0.2 0.2 rg');
        ops.push(`${bx + 2} ${yPos - barH - 10} Td`);
        ops.push(`(${col.name}) Tj`);
        ops.push('ET');
      }
      yPos -= (barH + 28);
      ops.push('Q');
    }

    // Typography scale test
    if (p.showTypeScale) {
      ops.push('q');
      ops.push('BT');
      ops.push('/F2 11 Tf');
      ops.push('0.12 0.15 0.18 rg');
      ops.push(`50 ${yPos} Td`);
      ops.push('(2. Typographic Scale & Rasterization Verification) Tj');
      ops.push('ET');
      yPos -= 22;

      const typeSpecs = [
        { font: '/F2', size: 16, text: 'Heading 16pt Bold - The quick brown fox jumps over the lazy dog' },
        { font: '/F1', size: 12, text: 'Body 12pt Regular - Pack my box with five dozen liquor jugs 1234567890' },
        { font: '/F3', size: 10, text: 'Monospace 10pt Courier - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4' },
        { font: '/F1', size: 8, text: 'Microtext 8pt - Standard fine print conformance test for laughing-adventure PDF verification' },
      ];

      for (let t = 0; t < typeSpecs.length; t++) {
        const item = typeSpecs[t];
        ops.push('BT');
        ops.push(`${item.font} ${item.size} Tf`);
        ops.push('0.15 0.18 0.24 rg');
        ops.push(`50 ${yPos} Td`);
        ops.push(`(${escapePdfText(item.text)}) Tj`);
        ops.push('ET');
        yPos -= (item.size + 8);
      }
      yPos -= 10;
      ops.push('Q');
    }

    // Sample data table
    if (p.showTable) {
      ops.push('q');
      ops.push('BT');
      ops.push('/F2 11 Tf');
      ops.push('0.12 0.15 0.18 rg');
      ops.push(`50 ${yPos} Td`);
      ops.push('(3. Structured Table Grid & Matrix Rendering) Tj');
      ops.push('ET');
      yPos -= 18;

      const tableCols = [100, 160, 140, 110];
      const tableHeaders = ['Test ID', 'Category', 'Specification', 'Status'];
      const tableRows = [
        ['PDF-001', 'Header Syntax', '%PDF-1.4 Magic Bytes', 'VERIFIED'],
        ['PDF-002', 'Font Metrics', 'Standard 14 Base Fonts', 'ACTIVE'],
        ['PDF-003', 'Cross-Ref Table', 'Traditional Subsection Xref', 'VALID'],
        ['PDF-004', 'Color Space', 'DeviceRGB & DeviceGray', 'CONFORMING']
      ];

      const startX = 50;
      const rowHeight = 18;

      // Header row
      let curX = startX;
      ops.push('0.90 0.93 0.96 rg');
      ops.push(`${startX} ${yPos - rowHeight} 510 ${rowHeight} re f`);

      for (let c = 0; c < tableHeaders.length; c++) {
        ops.push('BT');
        ops.push('/F2 9 Tf');
        ops.push('0.15 0.20 0.30 rg');
        ops.push(`${curX + 6} ${yPos - rowHeight + 5} Td`);
        ops.push(`(${tableHeaders[c]}) Tj`);
        ops.push('ET');
        curX += tableCols[c];
      }
      yPos -= rowHeight;

      // Table rows
      for (let r = 0; r < tableRows.length; r++) {
        const row = tableRows[r];
        if (r % 2 === 1) {
          ops.push('0.97 0.98 0.99 rg');
          ops.push(`${startX} ${yPos - rowHeight} 510 ${rowHeight} re f`);
        }
        curX = startX;
        for (let c = 0; c < row.length; c++) {
          ops.push('BT');
          ops.push(c === 3 ? '/F2 8 Tf' : '/F1 9 Tf');
          if (c === 3) {
            ops.push('0.08 0.55 0.25 rg'); // green
          } else {
            ops.push('0.20 0.25 0.30 rg');
          }
          ops.push(`${curX + 6} ${yPos - rowHeight + 5} Td`);
          ops.push(`(${row[c]}) Tj`);
          ops.push('ET');
          curX += tableCols[c];
        }
        yPos -= rowHeight;
      }

      // Border outline
      ops.push('0.75 0.80 0.88 RG 0.75 w');
      ops.push(`${startX} ${yPos} 510 ${rowHeight * (tableRows.length + 1)} re S`);
      yPos -= 20;
      ops.push('Q');
    }

    // Geometric Grid & Vector Line Alignment
    if (p.showGrid) {
      ops.push('q');
      ops.push('BT');
      ops.push('/F2 11 Tf');
      ops.push('0.12 0.15 0.18 rg');
      ops.push(`50 ${yPos} Td`);
      ops.push('(4. Vector Path Precision & Sub-pixel Line Weight Calibration) Tj');
      ops.push('ET');
      yPos -= 16;

      const weights = [0.25, 0.5, 1.0, 1.5, 2.0, 3.0];
      for (let w = 0; w < weights.length; w++) {
        const lineY = yPos - (w * 10);
        ops.push(`${weights[w]} w 0.2 0.3 0.4 RG`);
        ops.push(`50 ${lineY} m 280 ${lineY} l S`);
        // label
        ops.push('BT');
        ops.push('/F3 8 Tf 0.3 0.3 0.3 rg');
        ops.push(`290 ${lineY - 2} Td`);
        ops.push(`(${weights[w]} pt stroke) Tj`);
        ops.push('ET');
      }

      // Concentric circles & corner targets on the right
      const cx = 450;
      const cy = yPos - 25;
      ops.push('0.5 w 0.2 0.5 0.8 RG');
      ops.push(`${cx - 30} ${cy} m ${cx + 30} ${cy} l S`);
      ops.push(`${cx} ${cy - 30} m ${cx} ${cy + 30} l S`);
      // Circles
      ops.push(`${cx + 10} ${cy} m ${cx} ${cy} 10 0 360 arc S`);
      ops.push(`${cx + 20} ${cy} m ${cx} ${cy} 20 0 360 arc S`);
      ops.push(`${cx + 30} ${cy} m ${cx} ${cy} 30 0 360 arc S`);

      ops.push('Q');
    }

    // Page footer
    ops.push('q');
    ops.push('0.8 0.8 0.8 RG 0.5 w');
    ops.push('50 45 m 560 45 l S');

    ops.push('BT');
    ops.push('/F1 8 Tf');
    ops.push('0.5 0.5 0.5 rg');
    ops.push('50 32 Td');
    ops.push('(laughing-adventure - Test PDF Suite | AxelJohnson1988/laughing-adventure) Tj');
    ops.push('ET');

    ops.push('BT');
    ops.push('/F1 8 Tf');
    ops.push('0.5 0.5 0.5 rg');
    ops.push('500 32 Td');
    ops.push(`(Page ${i + 1} of ${pages.length}) Tj`);
    ops.push('ET');
    ops.push('Q');

    const streamBody = ops.join('\n');
    pageContents.push({ contentId, stream: streamBody });
  }

  // Info Object ID
  const infoObjId = nextObjId++;

  // Now construct all objects array with exact IDs:
  // 1: Catalog
  // 2: Outlines
  // 3: Pages tree
  // 4: Font F1 (Helvetica)
  // 5: Font F2 (Helvetica-Bold)
  // 6: Font F3 (Courier)
  // Page objects: pageObjIds
  // Content objects: pageContents
  // Info object: infoObjId

  const totalObjects = infoObjId;
  const objStrings: { id: number; text: string }[] = [];

  objStrings.push({
    id: 1,
    text: `1 0 obj\n<< /Type /Catalog /Pages 3 0 R /Outlines 2 0 R >>\nendobj`
  });

  objStrings.push({
    id: 2,
    text: `2 0 obj\n<< /Type /Outlines /Count 0 >>\nendobj`
  });

  objStrings.push({
    id: 3,
    text: `3 0 obj\n<< /Type /Pages /Kids [${pageObjIds.map(id => `${id} 0 R`).join(' ')}] /Count ${pages.length} >>\nendobj`
  });

  objStrings.push({
    id: 4,
    text: `4 0 obj\n<< /Type /Font /Subtype /Type1 /Name /F1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\nendobj`
  });

  objStrings.push({
    id: 5,
    text: `5 0 obj\n<< /Type /Font /Subtype /Type1 /Name /F2 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>\nendobj`
  });

  objStrings.push({
    id: 6,
    text: `6 0 obj\n<< /Type /Font /Subtype /Type1 /Name /F3 /BaseFont /Courier /Encoding /WinAnsiEncoding >>\nendobj`
  });

  for (let i = 0; i < pages.length; i++) {
    const pageId = pageObjIds[i];
    const contentId = pageContents[i].contentId;
    objStrings.push({
      id: pageId,
      text: `${pageId} 0 obj\n<< /Type /Page /Parent 3 0 R /MediaBox [0 0 612 792] /Contents ${contentId} 0 R /Resources << /Font << /F1 4 0 R /F2 5 0 R /F3 6 0 R >> /ProcSet [/PDF /Text /ImageB /ImageC /ImageI] >> >>\nendobj`
    });

    const stream = pageContents[i].stream;
    const streamLength = new TextEncoder().encode(stream).length;
    objStrings.push({
      id: contentId,
      text: `${contentId} 0 obj\n<< /Length ${streamLength} >>\nstream\n${stream}\nendstream\nendobj`
    });
  }

  // Info dict
  objStrings.push({
    id: infoObjId,
    text: `${infoObjId} 0 obj\n<< /Title (${escapePdfText(title)}) /Author (${escapePdfText(author)}) /Subject (${escapePdfText(subject)}) /Creator (${escapePdfText(creator)}) /CreationDate (${creationDate}) /Producer (laughing-adventure PDF-1.4 Generator) >>\nendobj`
  });

  // Sort objects by ID
  objStrings.sort((a, b) => a.id - b.id);

  // Build full PDF file with accurate byte offsets
  const header = `%PDF-1.4\n%\xE2\xE3\xCF\xD3\n`;
  const encoder = new TextEncoder();
  const chunks: Uint8Array[] = [];
  chunks.push(encoder.encode(header));
  let currentOffset = chunks[0].length;

  const offsets: number[] = [];
  // Object 0 is always dummy in xref
  offsets[0] = 0;

  for (const obj of objStrings) {
    offsets[obj.id] = currentOffset;
    const objBytes = encoder.encode(obj.text + '\n');
    chunks.push(objBytes);
    currentOffset += objBytes.length;
  }

  // Xref table
  const startXref = currentOffset;
  let xrefText = `xref\n0 ${totalObjects + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i <= totalObjects; i++) {
    const off = offsets[i] || 0;
    const padded = off.toString().padStart(10, '0');
    xrefText += `${padded} 00000 n \n`;
  }

  const trailerText = `trailer\n<< /Size ${totalObjects + 1} /Root 1 0 R /Info ${infoObjId} 0 R >>\nstartxref\n${startXref}\n%%EOF\n`;

  chunks.push(encoder.encode(xrefText));
  chunks.push(encoder.encode(trailerText));

  // Merge all chunks into single Uint8Array
  const totalLength = chunks.reduce((acc, c) => acc + c.length, 0);
  const result = new Uint8Array(totalLength);
  let pos = 0;
  for (const c of chunks) {
    result.set(c, pos);
    pos += c.length;
  }

  return result;
}

/**
 * Pre-configured sample PDF templates for immediate testing
 */
export function getSampleTemplates(): Array<{
  id: string;
  title: string;
  category: string;
  description: string;
  pageCount: number;
  generator: () => Uint8Array;
}> {
  return [
    {
      id: 'default-test',
      title: 'Standard Laughing Adventure Test Sheet',
      category: 'Diagnostic',
      description: 'Complete diagnostic test sheet with typography scale, RGB calibration bars, vector stroke weights, and matrix tables.',
      pageCount: 1,
      generator: () => generateTestPDF({
        title: 'Laughing Adventure: Standard Test Sheet',
        author: 'Jakob Axel Paper',
        subject: 'PDF Rendering Diagnostic Benchmark',
      })
    },
    {
      id: 'multipage-report',
      title: 'Multi-Page Test Document (3 Pages)',
      category: 'Pagination',
      description: 'Tests page-flipping, page tree traversal, headers, footers, and continuous pagination across multiple sheets.',
      pageCount: 3,
      generator: () => generateTestPDF({
        title: 'Laughing Adventure: Multi-Page Test Report',
        author: 'Jakob Axel Paper',
        subject: 'Pagination & Multi-Page Conformance',
        pages: [
          {
            title: 'Section 1: Architectural Overview & Protocol Test',
            contentLines: [
              'Page 1 verifies initial document structure and catalog node parsing.',
              'All font descriptors are linked to Base14 PostScript type definitions.',
              'Coordinate system uses standard 72 points per inch (DPI) MediaBox.'
            ],
            showColorBars: true,
            showTypeScale: false,
            showGrid: true,
            showTable: false
          },
          {
            title: 'Section 2: Typography & Font Metric Calibration',
            contentLines: [
              'Page 2 examines WinAnsi character encoding mapping.',
              'Validates kerning, baseline shift, and glyph rasterization accuracy.',
              'Supported standard fonts include Helvetica, Helvetica-Bold, and Courier.'
            ],
            showColorBars: false,
            showTypeScale: true,
            showGrid: false,
            showTable: true
          },
          {
            title: 'Section 3: Vector Graphics & Diagnostic Matrix',
            contentLines: [
              'Page 3 verifies clipping paths, line join/cap styles, and matrix operations.',
              'High-precision strokes are tested from hairline (0.25pt) to heavyweight (3pt).'
            ],
            showColorBars: true,
            showTypeScale: false,
            showGrid: true,
            showTable: true
          }
        ]
      })
    },
    {
      id: 'invoice-sample',
      title: 'Commercial Invoice & Form Test',
      category: 'Commercial',
      description: 'Structured commercial invoice layout testing tabular alignments, numerical data, and currency formatting.',
      pageCount: 1,
      generator: () => generateTestPDF({
        title: 'Commercial Tax Invoice - Test Sample',
        author: 'Jakob Axel Paper',
        subject: 'Invoice Layout & Alignment Testing',
        pages: [
          {
            title: 'TAX INVOICE: INV-2026-08492',
            contentLines: [
              'Billed To: Test Customer Corp, 100 Adventure Way, Tech District',
              'Issued Date: 2026-09-14   |   Due Date: 2026-10-14   |   PO Ref: PO-9941',
              'Payment Terms: Net 30 Days   |   Currency: USD ($)'
            ],
            showColorBars: false,
            showTypeScale: false,
            showGrid: false,
            showTable: true
          }
        ]
      })
    }
  ];
}
